
CREATE TABLE [dbo].[ESMA_INS_C]	
(	
	processed_date	date	NOT NULL,
	ID	int	identity(1,1)	NOT NULL,
	Fn_Id	nvarchar(12)	NOT NULL,
	Tr_Id	nvarchar(4)	NOT NULL,
	Fn_ClssfctnTp_ID	smallint,	
	Fn_FullNm_ID	int,	
	Fn_ShrtNm_ID	int,
	Fn_NtnlCcy_ID	tinyint,
	Fn_CmdtyDerivInd	bit,
	Tr_AdmssnApprvlDtByIssr	datetime2(0),
	Tr_FrstTradDt	datetime2(0),
	Tr_TermntnDt	datetime2(0),
	Tr_IssrReq	bit,
	Tr_ReqForAdmssnDt	datetime2(0),
	Issr_ID	int,	
	Dv_PricMltplr	decimal(18,17),
	Dv_UndrlygInstrm_Sngl_Indx_Nm_RefRate_Nm_ID	int,
	Dv_UndrlygInstrm_Sngl_ISIN_ID	int,	
	Tc_IncnsstncyInd	bit,
	Tc_LastUpd	datetime2(0),
	Tc_NvrPblshd	bit,
	Tc_PblctnPrd_Dt	date,
	Tc_PblctnPrd_FrDt	date,
	Tc_PblctnPrd_ToDt	date,
	Tc_PblctnPrd_FrDtToDt_FrDt	date,
	Tc_PblctnPrd_FrDtToDt_ToDt	date,
	Tc_RlvntCmptntAuthrty_ID	smallint,
	Tc_RlvntTradgVn_ID	smallint,
	is_terminated bit DEFAULT 0,
    is_cancelled bit DEFAULT 0,
	
	--CONSTRAINT [PK_dbo_ESMA_INS_C_ID]	PRIMARY KEY CLUSTERED COLUMNSTORE ([ID] ASC),
	--CONSTRAINT [UK_dbo_ESMA_INS_C_processed_date_Fn_Tr_Id]	UNIQUE NONCLUSTERED ([processed_date] ASC, [Fn_Id] ASC, [Tr_Id] ASC),
	INDEX	[CCIX_dbo_ESMA_INS_C]	CLUSTERED COLUMNSTORE,
	
	CONSTRAINT FK_dbo_ESMA_INS_C_Dv_UndrlygInstrm_Sngl_Indx_Nm_RefRate_Nm_ID	FOREIGN KEY (Dv_UndrlygInstrm_Sngl_Indx_Nm_RefRate_Nm_ID)	REFERENCES [dbo].[RefRate_Nm]	([ID]),
	CONSTRAINT FK_dbo_ESMA_INS_C_Dv_UndrlygInstrm_Sngl_ISIN_ID	FOREIGN KEY(Dv_UndrlygInstrm_Sngl_ISIN_ID)	REFERENCES [dbo].[ISINIdentifier]	([ID]),
	CONSTRAINT FK_dbo_ESMA_INS_C_Fn_ClssfctnTp_ID	FOREIGN KEY (Fn_ClssfctnTp_ID)	REFERENCES [dbo].[CFIIdentifier]	([ID]),
	CONSTRAINT FK_dbo_ESMA_INS_C_Fn_FullNm_ID	FOREIGN KEY (Fn_FullNm_ID)	REFERENCES [dbo].[FullNm]	([ID]),
	CONSTRAINT FK_dbo_ESMA_INS_C_Fn_NtnlCcy_ID	FOREIGN KEY (Fn_NtnlCcy_ID)	REFERENCES [dbo].[currency_iso_codes]	([ID]),
	CONSTRAINT FK_dbo_ESMA_INS_C_Fn_ShrtNm_ID	FOREIGN KEY (Fn_ShrtNm_ID)	REFERENCES [dbo].[ShrtNm]	([ID]),
	CONSTRAINT FK_dbo_ESMA_INS_C_Tc_RlvntCmptntAuthrty_ID	FOREIGN KEY (Tc_RlvntCmptntAuthrty_ID)	REFERENCES [dbo].[country_iso_codes]	([ID]),
	CONSTRAINT FK_dbo_ESMA_INS_C_Tc_RlvntTradgVn_ID	FOREIGN KEY (Tc_RlvntTradgVn_ID)	REFERENCES [dbo].[MICIdentifier]	([ID]),
	CONSTRAINT FK_dbo_ESMA_INS_C_Issr_ID	FOREIGN KEY (Issr_ID)	REFERENCES [dbo].[LEIIdentifier]	([ID]),
) ON [PS_dbo_ESMA_INS]([processed_date]);	
